"""changed products and errors

Revision ID: 1407e1833e97
Revises: a16995e8ad34
Create Date: 2025-11-09 19:30:16.239046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1407e1833e97'
down_revision: Union[str, Sequence[str], None] = 'a16995e8ad34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.DECIMAL(precision=16, scale=4), nullable=False))
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               type_=mysql.VARCHAR(length=3000),
               existing_nullable=True)
    op.alter_column('users', 'language_code',
               existing_type=sa.VARCHAR(length=255),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'language_code',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=mysql.VARCHAR(length=3000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('products', 'price')
    # ### end Alembic commands ###
